
name: Latest Instructables
on:
  schedule:
    # Runs every hour
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-readme-with-instructables:
    name: Update this repo's README with latest instructables
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "INSTRUCTABLES"
          feed_list: "https://www.instructables.com/member/daapplab/rss.xml"
