name: Get Google Play Reviews

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: install google play scraper
      run: |
        pip install google-play-scraper
    - name: run google play scraper
      run: |
        python scr/get_play_reviews.py
