name: Update README

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *

jobs:
  update_README:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: install python packages 
      run: |
        pip install google-play-scraper
        pip install requests 
    - name: generate updated README.md 
      run: |
        python src/generate_README.py
    - name: Commit new README.md
      run: |
        git config --global user.name 'CaptainDario'
        git config --global user.email 'daapplab@gmail.com'
        git commit -am "gen_README.md"
        git push