name: Update README

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: install google play scraper
      run: |
        pip install google-play-scraper
    - name: run google play scraper
      run: |
        python src/generate_README.py
    - name: output files
      run: |
        ls -a
    - name: Commit report
      run: |
        git config --global user.name 'CaptainDario'
        git config --global user.email 'daapplab@gmail.com'
        git commit -am "gen_README.md"
        git push